import React, { createContext, useContext, useState, useEffect } from 'react'
import { useAuth } from './AuthContext'

const ThemeLangContext = createContext()

const translations = {
  vi: {
    "hệ thống ck go": "Hệ thống Convenia",
    "thức ăn & thức uống": "Thức ăn & Thức uống",
    "thức ăn": "Thức ăn",
    "thức uống": "Thức uống",
    "tất cả menu": "Tất cả Menu",
    "đăng nhập": "Đăng nhập",
    "đăng xuất": "Đăng xuất",
    "thông tin cá nhân": "Thông tin cá nhân",
    "quản lý kho": "Quản lý kho",
    "cửa hàng": "Cửa hàng",
    "đang xác định...": "Đang xác định...",
    "giỏ hàng": "Giỏ hàng",
    "tìm sản phẩm...": "Tìm sản phẩm...",
    "tài khoản": "Tài khoản",
    "dịch vụ tiện ích": "Dịch vụ tiện ích",
    "ck go tự hào cung cấp các dịch vụ tiện ích đa dạng và chất lượng nhất": "Convenia tự hào cung cấp các dịch vụ tiện ích đa dạng và chất lượng nhất",
    "sản phẩm nổi bật": "Sản phẩm nổi bật",
    "đăng ký nhận tin khuyến mãi": "Đăng ký nhận tin khuyến mãi",
    "nhập email của bạn...": "Nhập email của bạn...",
    "đăng ký": "Đăng ký",
    "phòng chăm sóc khách hàng": "Phòng Chăm sóc khách hàng",
    "địa chỉ": "Địa chỉ",
    "ngày cấp": "Ngày cấp",
    "nơi cấp": "Nơi cấp",
    "ưu đãi đặc biệt": "Ưu đãi đặc biệt",
    "flash sale chớp nhoáng": "FLASH SALE CHỚP NHOÁNG",
    "kết thúc trong": "Kết thúc trong",
    "đang tải sản phẩm khuyến mãi từ hệ thống...": "Đang tải sản phẩm khuyến mãi từ hệ thống...",
    "gửi": "Gửi",
    "hệ thống cửa hàng": "HỆ THỐNG CỬA HÀNG",
    "sản phẩm & dịch vụ": "SẢN PHẨM & DỊCH VỤ",
    "giới thiệu": "Giới Thiệu",
    "cơ hội nghề nghiệp": "Cơ Hội Nghề Nghiệp",
    "tin tức & sự kiện": "Tin Tức & Sự Kiện",
    "liên hệ": "Liên Hệ",
    "điều khoản sử dụng": "Điều Khoản Sử Dụng",
    "chính sách": "Chính Sách",
    "hóa đơn đỏ": "Hóa Đơn Đỏ",
    "ck convenience store vietnam - chuỗi cửa hàng tiện lợi - mở cửa 24/7": "CK Convenience Store Vietnam - Chuỗi cửa hàng tiện lợi - Mở cửa 24/7",
    "công ty tnhh bán lẻ ck việt nam - giấy cnđkdn: 0306182043": "CÔNG TY TNHH BÁN LẺ CK VIỆT NAM - Giấy CNĐKDN: 0306182043",
    "ngày cấp: 10/11/2008. nơi cấp: sở kế hoạch - đầu tư tp. hồ chí minh": "Ngày cấp: 10/11/2008. Nơi cấp: Sở Kế hoạch - Đầu tư Tp. Hồ Chí Minh",
    "địa chỉ: 160 bùi thị xuân, phường bến thành, quận 1, thành phố hồ chí minh, việt nam.": "Địa chỉ: 160 Bùi Thị Xuân, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh, Việt Nam.",
    "phòng chăm sóc khách hàng: 1900.3110": "Phòng Chăm sóc khách hàng: 1900.3110",
    "email: info@ckstores.com.vn": "Email: info@ckstores.com.vn",
    "bộ lọc sản phẩm": "Bộ lọc sản phẩm",
    "chọn chi nhánh": "Chọn chi nhánh",
    "tất cả chi nhánh": "Tất cả chi nhánh",
    "chi nhánh": "Chi nhánh",
    "mức giá": "Mức giá",
    "tất cả mức giá": "Tất cả mức giá",
    "dưới 15.000đ": "Dưới 15.000đ",
    "15.000đ - 30.000đ": "15.000đ - 30.000đ",
    "trên 30.000đ": "Trên 30.000đ",
    "sắp xếp": "Sắp xếp",
    "mặc định": "Mặc định",
    "giá tăng dần": "Giá tăng dần",
    "giá giảm dần": "Giá giảm dần",
    "còn lại": "Còn lại",
    "phần": "phần",
    "cái": "cái",
    "lon": "lon",
    "chai": "chai",
    "ly": "ly",
    "mua ngay": "Mua ngay",
    "hết hàng": "Hết hàng",
    "thêm vào giỏ hàng": "Thêm vào giỏ hàng",
    "giỏ hàng của bạn": "Giỏ hàng của bạn",
    "tổng tiền": "Tổng tiền",
    "tiến hành thanh toán": "Tiến hành thanh toán",
    "thông tin giao hàng": "Thông tin giao hàng",
    "họ và tên": "Họ và tên",
    "số điện thoại": "Số điện thoại",
    "địa chỉ nhận hàng": "Địa chỉ nhận hàng",
    "chọn phương thức thanh toán": "Chọn phương thức thanh toán",
    "thanh toán khi nhận hàng (cod)": "Thanh toán khi nhận hàng (COD)",
    "chuyển khoản ngân hàng qua vietqr": "Chuyển khoản ngân hàng qua VietQR",
    "hoàn tất thanh toán": "Hoàn tất thanh toán",
    "giỏ hàng trống": "Giỏ hàng của bạn đang trống",
    "quay lại mua sắm": "Quay lại mua sắm",
    "tiếp tục mua hàng": "Tiếp tục mua hàng",
    "đang tải giỏ hàng...": "Đang tải giỏ hàng...",
    "tóm tắt đơn hàng": "Tóm tắt đơn hàng",
    "tạm tính": "Tạm tính",
    "phí vận chuyển": "Phí vận chuyển",
    "miễn phí": "Miễn phí",
    "tổng cộng": "Tổng cộng",
    "thanh toán với vietqr": "THANH TOÁN VỚI VIETQR",
    "đang xử lý đơn hàng...": "Đang xử lý đơn hàng...",
    "xác thực thanh toán (email otp)": "Xác thực thanh toán (Email OTP)",
    "nhập mã otp 6 chữ số đã được gửi đến email của bạn để xác nhận giao dịch": "Nhập mã OTP 6 chữ số đã được gửi đến email của bạn để xác nhận giao dịch",
    "xác nhận thanh toán": "Xác nhận thanh toán",
    "thanh toán chuyển khoản vietqr": "Thanh toán chuyển khoản VietQR",
    "vui lòng quét mã qr dưới đây bằng app ngân hàng để thanh toán": "Vui lòng quét mã QR dưới đây bằng app Ngân hàng để thanh toán",
    "tìm kiếm cửa hàng": "Tìm kiếm cửa hàng",
    "nhập tên đường, quận...": "Nhập tên đường, quận...",
    "đóng cửa": "Đóng cửa",
    "mở cửa 24/7": "Mở cửa 24/7",
    "khoảng cách": "Khoảng cách",
    "đường đi": "Đường đi",
    "chọn làm cửa hàng mặc định": "Chọn làm cửa hàng mặc định",
    "cửa hàng mặc định": "Cửa hàng mặc định",
    "tính khoảng cách từ vị trí của tôi": "Tính khoảng cách từ vị trí của tôi",
    "chỉ đường đi": "Chỉ đường đi",
    "quản lý thông tin tài khoản": "Quản lý thông tin tài khoản",
    "email đăng nhập": "Email đăng nhập",
    "ngày sinh": "Ngày sinh",
    "cửa hàng gần nhất": "Cửa hàng gần nhất",
    "lịch sử đơn hàng": "Lịch sử đơn hàng",
    "xác thực hai yếu tố (2fa)": "Xác thực hai yếu tố (2FA)",
    "thiết lập fido2 / passkey": "Thiết lập FIDO2 / Passkey",
    "lưu thay đổi": "Lưu thay đổi",
    "kích hoạt 2fa": "Kích hoạt 2FA",
    "hủy kích hoạt 2fa": "Hủy kích hoạt 2FA",
    "đăng ký passkey mới": "Đăng ký Passkey mới",
    "bạn chưa có đơn hàng nào.": "Bạn chưa có đơn hàng nào.",
    "hồ sơ thành viên ck go": "Hồ sơ thành viên Convenia",
    "nhập họ tên": "Nhập họ tên",
    "nhập số điện thoại": "Nhập số điện thoại",
    "cửa hàng ck go gần nhất": "Cửa hàng Convenia gần nhất",
    "nhấn nút để tìm store...": "Nhấn nút để tìm store...",
    "-- chọn chi nhánh --": "-- Chọn chi nhánh --",
    "địa chỉ nhận hàng chi tiết": "Địa chỉ nhận hàng chi tiết",
    "số nhà, tên đường...": "Số nhà, tên đường...",
    "xác thực sinh trắc học (fido2)": "Xác thực sinh trắc học (FIDO2)",
    "đăng ký thiết bị an toàn (windows hello / touch id) để đăng nhập và thanh toán nhanh không cần mật khẩu.": "Đăng ký thiết bị an toàn (Windows Hello / Touch ID) để đăng nhập và thanh toán nhanh không cần mật khẩu.",
    "đăng ký thiết bị bảo mật": "Đăng ký thiết bị bảo mật",
    "xem lịch sử mua hàng": "Xem lịch sử mua hàng",
    "chi tiết đơn hàng": "Chi tiết đơn hàng",
    "mã đơn hàng": "Mã đơn hàng",
    "trạng thái": "Trạng thái",
    "thời gian": "Thời gian",
    "thành tiền": "Thành tiền",
    "tên đăng nhập / email": "Tên đăng nhập / Email",
    "mật khẩu": "Mật khẩu",
    "ít nhất 6 ký tự (chữ & số)": "Ít nhất 6 ký tự (chữ & số)",
    "nhập lại mật khẩu": "Nhập lại mật khẩu",
    "mật khẩu không trùng khớp!": "Mật khẩu không trùng khớp!",
    "có ít nhất 1 chữ cái (a-z)": "Có ít nhất 1 chữ cái (a-z)",
    "có ít nhất 1 chữ số (0-9)": "Có ít nhất 1 chữ số (0-9)",
    "độ dài tối thiểu 6 ký tự": "Độ dài tối thiểu 6 ký tự",
    "ghi nhớ": "Ghi nhớ",
    "quên mật khẩu?": "Quên mật khẩu?",
    "đăng nhập ngay": "Đăng nhập ngay",
    "đăng nhập bằng thiết bị an toàn": "Đăng nhập bằng thiết bị an toàn",
    "quay lại đăng nhập": "Quay lại đăng nhập",
    "khôi phục mật khẩu": "Khôi phục mật khẩu",
    "email đăng ký": "Email đăng ký",
    "nhập email của bạn": "Nhập email của bạn",
    "nhập mã otp đã gửi đến email": "Nhập mã OTP đã gửi đến Email",
    "nhập mã xác thực 2fa từ ứng dụng authenticator": "Nhập mã xác thực 2FA từ ứng dụng Authenticator",
    "mật khẩu mới": "Mật khẩu mới",
    "xác nhận mật khẩu mới": "Xác nhận mật khẩu mới",
    "nhập lại mật khẩu mới": "Nhập lại mật khẩu mới",
    "gửi mã otp": "GỬI MÃ OTP",
    "chào mừng!": "Chào mừng!",
    "khám phá thế giới tiện lợi tại ck go.": "Khám phá thế giới tiện lợi tại Convenia.",
    "bạn chưa có tài khoản?": "Bạn chưa có tài khoản?",
    "đăng ký ngay": "ĐĂNG KÝ NGAY",
    "xác thực 2 lớp (2fa)": "Xác thực 2 lớp (2FA)",
    "quét mã qr bằng ứng dụng google authenticator để kích hoạt 2fa.": "Quét mã QR bằng ứng dụng Google Authenticator để kích hoạt 2FA.",
    "hoặc nhập mã tay": "Hoặc nhập mã tay",
    "nhập mã xác thực 6 chữ số từ ứng dụng trên điện thoại của bạn": "Nhập mã xác thực 6 chữ số từ ứng dụng trên điện thoại của bạn",
    "xác nhận đăng nhập": "Xác nhận đăng nhập",
    "thiết lập lại 2fa (quét mã qr mới)": "Thiết lập lại 2FA (Quét mã QR mới)",
    "quản lý kho ck go": "Quản lý kho Convenia",
    "bảng quản trị kho": "Bảng quản trị kho",
    "thống kê kho": "Thống kê kho",
    "tổng số sản phẩm": "Tổng số sản phẩm",
    "hết hàng / sắp hết": "Hết hàng / sắp hết",
    "lịch sử cập nhật": "Lịch sử cập nhật",
    "thêm sản phẩm mới": "Thêm sản phẩm mới",
    "tên sản phẩm": "Tên sản phẩm",
    "số lượng": "Số lượng",
    "đơn vị": "Đơn vị",
    "hành động": "Hành động",
    "nhập kho": "Nhập kho",
    "xuất kho": "Xuất kho",
    "người thực hiện": "Người thực hiện",
    "tải ảnh": "Tải ảnh",
    "lưu sản phẩm": "Lưu sản phẩm",
    "về trang chủ": "Về trang chủ",
    "hủy": "Hủy",
    "lịch sử nhập xuất": "Lịch sử nhập xuất",
    "thoát": "Thoát",
    "quản lý tồn kho - bình thạnh": "Quản lý Tồn kho - Bình Thạnh",
    "xin chào": "Xin chào",
    "chọn chi nhánh quản lý": "Chọn chi nhánh quản lý",
    "hình ảnh": "Hình ảnh",
    "loại": "Loại",
    "tồn kho": "Tồn kho",
    "giá bán": "Giá bán",
    "mã sản phẩm (tự động)": "Mã sản phẩm (Tự động)",
    "chọn loại sản phẩm": "Chọn loại sản phẩm",
    "giá bán (vnđ)": "Giá bán (VNĐ)",
    "số lượng tồn": "Số lượng tồn",
    "số lượng hiện có": "Số lượng hiện có",
    "hình ảnh sản phẩm (từ máy)": "Hình ảnh sản phẩm (Từ máy)",
    "lưu vào kho": "LƯU VÀO KHO",
    "quay lại web": "Quay lại Web",
    "lịch sử nhập/xuất kho realtime": "Lịch sử Nhập/Xuất Kho Realtime",
    "dữ liệu được cập nhật tự động khi có biến động kho": "Dữ liệu được cập nhật tự động khi có biến động kho",
    "đang quét sản phẩm tại chi nhánh...": "Đang quét sản phẩm tại chi nhánh...",
    "chi nhánh này hiện chưa có sản phẩm thuộc mục này.": "Chi nhánh này hiện chưa có sản phẩm thuộc mục này.",
    "lỗi tải dữ liệu. vui lòng kiểm tra kết nối với máy chủ api.": "Lỗi tải dữ liệu. Vui lòng kiểm tra kết nối với máy chủ API.",
    "bạn ơi, bạn cần đăng nhập để mua hàng nhé!": "Bạn ơi, bạn cần đăng nhập để mua hàng nhé!",
    "không tìm thấy sản phẩm nào khớp với": "Không tìm thấy sản phẩm nào khớp với",
    "quản lý tài khoản": "Quản lý tài khoản",
    "cập nhật hồ sơ cá nhân và quản lý bảo mật nâng cao": "Cập nhật hồ sơ cá nhân và quản lý bảo mật nâng cao",
    "chức vụ": "Chức vụ",
    "cập nhật thông tin tài khoản thành công!": "Cập nhật thông tin tài khoản thành công!",
    "lỗi cập nhật!": "Lỗi cập nhật!",
    "thiết bị hoặc trình duyệt này không hỗ trợ fido2/webauthn bảo mật!": "Thiết bị hoặc trình duyệt này không hỗ trợ FIDO2/WebAuthn bảo mật!",
    "nhập mật khẩu hiện tại của bạn để liên kết thiết bị bảo mật này:": "Nhập mật khẩu hiện tại của bạn để liên kết thiết bị bảo mật này:",
    "liên kết thất bại: bạn chưa xác nhận mật khẩu.": "Liên kết thất bại: Bạn chưa xác nhận mật khẩu.",
    "xác nhận mật khẩu thất bại! vui lòng điền đúng mật khẩu tài khoản.": "Xác nhận mật khẩu thất bại! Vui lòng điền đúng mật khẩu tài khoản.",
    "đã liên kết thiết bị bảo mật vân tay/gương mặt fido2 thành công!": "Đã liên kết thiết bị bảo mật vân tay/gương mặt FIDO2 thành công!",
    "đăng ký fido2 không thành công trên server!": "Đăng ký FIDO2 không thành công trên server!",
    "thao tác bị hủy hoặc trình duyệt không được cấp quyền sinh trắc học.": "Thao tác bị hủy hoặc trình duyệt không được cấp quyền sinh trắc học.",
    "lỗi kết nối fido2!": "Lỗi kết nối FIDO2!",
    "đã tắt xác thực 2 lớp totp!": "Đã tắt xác thực 2 lớp TOTP!",
    "vui lòng nhập đủ 6 chữ số totp!": "Vui lòng nhập đủ 6 chữ số TOTP!",
    "đã bật thành công bảo mật 2 lớp totp!": "Đã bật thành công bảo mật 2 lớp TOTP!",
    "mã 2fa không chính xác!": "Mã 2FA không chính xác!",
    "đang quét vị trí của bạn...": "Đang quét vị trí của bạn...",
    "đã tìm thấy cửa hàng gần nhất": "Đã tìm thấy cửa hàng gần nhất",
    "không thể lấy vị trí. vui lòng bật quyền định vị!": "Không thể lấy vị trí. Vui lòng bật quyền định vị!",
    "không thể định vị gps!": "Không thể định vị GPS!",
    "trình duyệt không hỗ trợ geolocation!": "Trình duyệt không hỗ trợ Geolocation!",
    "bảo mật nâng cao": "Bảo mật nâng cao",
    "khóa fido2 / webauthn": "Khóa FIDO2 / WebAuthn",
    "đã bật": "ĐÃ BẬT",
    "tắt": "TẮT",
    "đăng nhập nhanh bằng cảm biến vân tay hoặc nhận diện khuôn mặt mà không cần nhập mật khẩu.": "Đăng nhập nhanh bằng cảm biến vân tay hoặc nhận diện khuôn mặt mà không cần nhập mật khẩu.",
    "liên kết khóa bảo mật": "Liên kết Khóa Bảo Mật",
    "xác thực 2 lớp (totp)": "Xác thực 2 lớp (TOTP)",
    "bảo vệ tài khoản bằng mã bảo mật 6 số từ google authenticator / microsoft authenticator.": "Bảo vệ tài khoản bằng mã bảo mật 6 số từ Google Authenticator / Microsoft Authenticator.",
    "tắt 2fa": "Tắt 2FA",
    "thiết lập 2fa": "Thiết Lập 2FA",
    "mã khóa (secret key)": "Mã Khóa (Secret Key)",
    "đã copy mã 2fa secret!": "Đã copy mã 2FA secret!",
    "nhập mã 6 số từ ứng dụng:": "Nhập mã 6 số từ ứng dụng:",
    "xác nhận kích hoạt 2fa": "Xác Nhận Kích Hoạt 2FA",
    "hủy bỏ": "Hủy Bỏ",
    "hồ sơ cá nhân": "Hồ Sơ Cá Nhân",
    "email (không đổi)": "Email (Không đổi)",
    "địa chỉ giao hàng": "Địa Chỉ Giao Hàng",
    "cửa hàng gần nhất (giao nhanh)": "Cửa hàng gần nhất (Giao nhanh)",
    "vui lòng nhập mã bảo mật 2 lớp (totp) để tiếp tục!": "Vui lòng nhập mã bảo mật 2 lớp (TOTP) để tiếp tục!",
    "đăng nhập thành công! đang chuyển hướng...": "Đăng nhập thành công! Đang chuyển hướng...",
    "đăng ký tài khoản thành công! hãy đăng nhập ngay.": "Đăng ký tài khoản thành công! Hãy đăng nhập ngay.",
    "có lỗi xảy ra!": "Có lỗi xảy ra!",
    "mã otp 2fa phải gồm đúng 6 chữ số!": "Mã OTP 2FA phải gồm đúng 6 chữ số!",
    "mã bảo mật 2fa không chính xác!": "Mã bảo mật 2FA không chính xác!",
    "lỗi xác thực: ": "Lỗi xác thực: ",
    "trình duyệt hoặc thiết bị của bạn không hỗ trợ fido2/webauthn!": "Trình duyệt hoặc thiết bị của bạn không hỗ trợ FIDO2/WebAuthn!",
    "thiết bị bảo mật chưa được đăng ký hoặc không khớp!": "Thiết bị bảo mật chưa được đăng ký hoặc không khớp!",
    "xác thực vân tay/fido2 thành công! đang vào hệ thống...": "Xác thực vân tay/FIDO2 thành công! Đang vào hệ thống...",
    "đã hủy thao tác vân tay sinh trắc học.": "Đã hủy thao tác vân tay sinh trắc học.",
    "lỗi xác thực thiết bị fido2!": "Lỗi xác thực thiết bị FIDO2!",
    "xác thực hai lớp": "Xác thực hai lớp",
    "chào mừng trở lại": "Chào mừng trở lại",
    "đăng ký thành viên": "Đăng ký thành viên",
    "nhập mã otp 6 số từ google authenticator trên thiết bị của bạn": "Nhập mã OTP 6 số từ Google Authenticator trên thiết bị của bạn",
    "đăng nhập để nhận ngập tràn ưu đãi tại convenia": "Đăng nhập để nhận ngập tràn ưu đãi tại Convenia",
    "gia nhập convenia premium chỉ trong vài giây": "Gia nhập Convenia Premium chỉ trong vài giây",
    "mã bảo mật otp (2fa)": "Mã bảo mật OTP (2FA)",
    "xác nhận & đăng nhập": "Xác nhận & đăng nhập",
    "địa chỉ email": "Địa chỉ Email",
    "tạo tài khoản": "Tạo tài khoản",
    "hoặc đăng nhập nhanh": "Hoặc đăng nhập nhanh",
    "đăng nhập với vân tay / fido2": "Đăng nhập với vân tay / FIDO2",
    "chưa có tài khoản? đăng ký ngay": "Chưa có tài khoản? Đăng ký ngay",
    "đã có tài khoản? đăng nhập ngay": "Đã có tài khoản? Đăng nhập ngay",
    "lịch sử mua hàng": "Lịch sử mua hàng",
    "danh sách các đơn hàng đã đặt thành công tại hệ thống convenia": "Danh sách các đơn hàng đã đặt thành công tại hệ thống Convenia",
    "chưa có đơn hàng nào!": "Chưa có đơn hàng nào!",
    "hãy đặt món đồ đầu tiên để bắt đầu lưu lịch sử.": "Hãy đặt món đồ đầu tiên để bắt đầu lưu lịch sử.",
    "mua sắm ngay": "Mua sắm ngay",
    "tổng thanh toán": "Tổng thanh toán",
    "danh sách món ăn": "Danh sách món ăn",
    "số lượng: ": "Số lượng: ",
    "còn hàng": "Còn hàng",
    "trang quản trị hệ thống": "Trang Quản Trị Hệ Thống",
    "cấu hình sản phẩm, kiểm soát số lượng kho hàng tiện lợi": "Cấu hình sản phẩm, kiểm soát số lượng kho hàng tiện lợi",
    "quản lý sản phẩm": "Quản Lý Sản Phẩm",
    "nhật ký kho hàng": "Nhật Ký Kho Hàng",
    "cửa hàng:": "Cửa hàng:",
    "ảnh": "Ảnh",
    "mã pid": "Mã PID",
    "danh mục": "Danh Mục",
    "đơn giá": "Đơn Giá",
    "flash sale": "Flash Sale",
    "đồ ăn": "Đồ Ăn",
    "nước uống": "Nước uống",
    "sửa": "Sửa",
    "xóa": "Xóa",
    "phân loại": "Phân Loại",
    "cập nhật sản phẩm": "Cập Nhật Sản Phẩm",
    "số lượng kho": "Số Lượng Kho",
    "đơn vị tính": "Đơn Vị Tính",
    "chi nhánh cửa hàng": "Chi Nhánh Cửa Hàng",
    "đường dẫn ảnh": "Đường Dẫn Ảnh",
    "đang tải...": "Đang tải...",
    "tải lên": "Tải Lên",
    "sản phẩm tham gia flash sale": "Sản phẩm tham gia Flash Sale",
    "giảm %": "Giảm %",
    "cập nhật": "Cập Nhật",
    "thêm mới": "Thêm Mới",
    "tải hình ảnh lên thành công!": "Tải hình ảnh lên thành công!",
    "lỗi upload file!": "Lỗi upload file!",
    "đã chỉnh sửa sản phẩm!": "Đã chỉnh sửa sản phẩm!",
    "đã thêm sản phẩm thành công!": "Đã thêm sản phẩm thành công!",
    "thao tác sản phẩm thất bại!": "Thao tác sản phẩm thất bại!",
    "bạn có chắc chắn muốn xóa sản phẩm ": "Bạn có chắc chắn muốn xóa sản phẩm ",
    " không?": " không?",
    "đã xóa sản phẩm khỏi hệ thống!": "Đã xóa sản phẩm khỏi hệ thống!",
    "không thể xóa sản phẩm!": "Không thể xóa sản phẩm!",
    "đổi giao diện": "Đổi giao diện",
    "sáng": "Sáng",
    "tối": "Tối",
    "thay đổi ngôn ngữ": "Thay đổi ngôn ngữ",
    "giao diện & ngôn ngữ": "Giao diện & Ngôn ngữ",
    "quản trị": "Quản Trị",
    "trang cá nhân": "Trang Cá Nhân",
    "bảng quản trị admin": "Bảng Quản Trị Admin",
    "trang chủ": "Trang Chủ",
    "thực đơn": "Thực Đơn",
    "tìm kiếm": "Tìm Kiếm",
    "chỉ còn": "Chỉ còn",
    "sản phẩm trong kho!": "sản phẩm trong kho!"
  },
  en: {
    "hệ thống ck go": "Convenia Stores",
    "thức ăn & thức uống": "Food & Drinks",
    "thức ăn": "Food",
    "thức uống": "Drinks",
    "tất cả menu": "Full Menu",
    "đăng nhập": "Log In",
    "đăng xuất": "Log Out",
    "thông tin cá nhân": "My Profile",
    "quản lý kho": "Admin",
    "cửa hàng": "Store",
    "đang xác định...": "Locating...",
    "giỏ hàng": "Cart",
    "tìm sản phẩm...": "Search products...",
    "tài khoản": "Account",
    "dịch vụ tiện ích": "Convenience Services",
    "ck go tự hào cung cấp các dịch vụ tiện ích đa dạng và chất lượng nhất": "Convenia is proud to provide the most diverse and high-quality services",
    "sản phẩm nổi bật": "Featured Products",
    "đăng ký nhận tin khuyến mãi": "Subscribe to Newsletter",
    "nhập email của bạn...": "Enter your email...",
    "đăng ký": "Subscribe",
    "phòng chăm sóc khách hàng": "Customer Care",
    "địa chỉ": "Address",
    "ngày cấp": "Issue Date",
    "nơi cấp": "Issued By",
    "ưu đãi đặc biệt": "Special Offers",
    "flash sale chớp nhoáng": "FLASH SALE",
    "kết thúc trong": "Ends in",
    "đang tải sản phẩm khuyến mãi từ hệ thống...": "Loading promo products from system...",
    "gửi": "Send",
    "hệ thống cửa hàng": "STORE LOCATOR",
    "sản phẩm & dịch vụ": "PRODUCTS & SERVICES",
    "giới thiệu": "About Us",
    "cơ hội nghề nghiệp": "Careers",
    "tin tức & sự kiện": "News & Events",
    "liên hệ": "Contact Us",
    "điều khoản sử dụng": "Terms of Use",
    "chính sách": "Privacy Policy",
    "hóa đơn đỏ": "E-Invoice",
    "ck convenience store vietnam - chuỗi cửa hàng tiện lợi - mở cửa 24/7": "CK Convenience Store Vietnam - Convenience Store Chain - Open 24/7",
    "công ty tnhh bán lẻ ck việt nam - giấy cnđkdn: 0306182043": "CK VIETNAM RETAIL CO., LTD - Business Registration No: 0306182043",
    "ngày cấp: 10/11/2008. nơi cấp: sở kế hoạch - đầu tư tp. hồ chí minh": "Issued on: 10/11/2008. Issued by: HCMC Department of Planning and Investment",
    "địa chỉ: 160 bùi thị xuân, phường bến thành, quận 1, thành phố hồ chí minh, việt nam.": "Address: 160 Bui Thi Xuan, Ben Thanh Ward, District 1, Ho Chi Minh City, Vietnam.",
    "phòng chăm sóc khách hàng: 1900.3110": "Customer Support: 1900.3110",
    "email: info@ckstores.com.vn": "Email: info@ckstores.com.vn",
    "bộ lọc sản phẩm": "Product Filters",
    "chọn chi nhánh": "Select Branch",
    "tất cả chi nhánh": "All Branches",
    "chi nhánh": "Branch",
    "mức giá": "Price Range",
    "tất cả mức giá": "All Prices",
    "dưới 15.000đ": "Under 15,000 VND",
    "15.000đ - 30.000đ": "15,000 - 30,000 VND",
    "trên 30.000đ": "Over 30,000 VND",
    "sắp xếp": "Sort By",
    "mặc định": "Default",
    "giá tăng dần": "Price: Low to High",
    "giá giảm dần": "Price: High to Low",
    "còn lại": "In Stock",
    "phần": "portion",
    "cái": "pcs",
    "lon": "can",
    "chai": "bottle",
    "ly": "cup",
    "mua ngay": "Buy Now",
    "hết hàng": "Out of Stock",
    "thêm vào giỏ hàng": "Add to Cart",
    "giỏ hàng của bạn": "Your Shopping Cart",
    "tổng tiền": "Total Amount",
    "tiến hành thanh toán": "Proceed to Checkout",
    "thông tin giao hàng": "Shipping Information",
    "họ và tên": "Full Name",
    "số điện thoại": "Phone Number",
    "địa chỉ nhận hàng": "Shipping Address",
    "chọn phương thức thanh toán": "Select Payment Method",
    "thanh toán khi nhận hàng (cod)": "Cash on Delivery (COD)",
    "chuyển khoản ngân hàng qua vietqr": "Bank Transfer (VietQR)",
    "hoàn tất thanh toán": "Place Order",
    "giỏ hàng trống": "Your cart is empty",
    "quay lại mua sắm": "Continue Shopping",
    "tiếp tục mua hàng": "Continue Shopping",
    "đang tải giỏ hàng...": "Loading cart...",
    "tóm tắt đơn hàng": "Order Summary",
    "tạm tính": "Subtotal",
    "phí vận chuyển": "Shipping Fee",
    "miễn phí": "Free",
    "tổng cộng": "Total",
    "thanh toán với vietqr": "PAY WITH VIETQR",
    "đang xử lý đơn hàng...": "Processing order...",
    "xác thực thanh toán (email otp)": "Payment Verification (Email OTP)",
    "nhập mã otp 6 chữ số đã được gửi đến email của bạn để xác nhận giao dịch": "Enter the 6-digit OTP sent to your email to confirm the transaction",
    "xác nhận thanh toán": "Confirm Payment",
    "thanh toán chuyển khoản vietqr": "VietQR Bank Transfer Payment",
    "vui lòng quét mã qr dưới đây bằng app ngân hàng để thanh toán": "Please scan the QR code below with your banking app to pay",
    "tìm kiếm cửa hàng": "Find Stores",
    "nhập tên đường, quận...": "Enter street or district...",
    "đóng cửa": "Closed",
    "mở cửa 24/7": "Open 24/7",
    "khoảng cách": "Distance",
    "đường đi": "Directions",
    "chọn làm cửa hàng mặc định": "Set as Default",
    "cửa hàng mặc định": "Default Store",
    "tính khoảng cách từ vị trí của tôi": "Calculate distance from my location",
    "chỉ đường đi": "Get Directions",
    "quản lý thông tin tài khoản": "Manage Profile",
    "email đăng nhập": "Login Email",
    "ngày sinh": "Date of Birth",
    "cửa hàng gần nhất": "Nearest Store",
    "lịch sử đơn hàng": "Order History",
    "xác thực hai yếu tố (2fa)": "Two-Factor Auth (2FA)",
    "thiết lập fido2 / passkey": "FIDO2 / Passkey Setup",
    "lưu thay đổi": "Save Changes",
    "kích hoạt 2fa": "Enable 2FA",
    "hủy kích hoạt 2fa": "Disable 2FA",
    "đăng ký passkey mới": "Register Passkey",
    "bạn chưa có đơn hàng nào.": "You have no order history.",
    "hồ sơ thành viên ck go": "Convenia Member Profile",
    "nhập họ tên": "Enter full name",
    "nhập số điện thoại": "Enter phone number",
    "cửa hàng ck go gần nhất": "Nearest Convenia Store",
    "nhấn nút để tìm store...": "Click button to find stores...",
    "-- chọn chi nhánh --": "-- Select branch --",
    "địa chỉ nhận hàng chi tiết": "Detailed shipping address",
    "số nhà, tên đường...": "House number, street name...",
    "xác thực sinh trắc học (fido2)": "Biometric Verification (FIDO2)",
    "đăng ký thiết bị an toàn (windows hello / touch id) để đăng nhập và thanh toán nhanh không cần mật khẩu.": "Register secure device (Windows Hello / Touch ID) for passwordless login and checkout.",
    "đăng ký thiết bị bảo mật": "Register Security Device",
    "xem lịch sử mua hàng": "View Order History",
    "chi tiết đơn hàng": "Order Details",
    "mã đơn hàng": "Order ID",
    "trạng thái": "Status",
    "thời gian": "Date",
    "thành tiền": "Total Amount",
    "tên đăng nhập / email": "Username / Email",
    "mật khẩu": "Password",
    "ít nhất 6 ký tự (chữ & số)": "At least 6 characters (letters & numbers)",
    "nhập lại mật khẩu": "Confirm Password",
    "mật khẩu không trùng khớp!": "Passwords do not match!",
    "có ít nhất 1 chữ cái (a-z)": "At least 1 letter (a-z)",
    "có ít nhất 1 chữ số (0-9)": "At least 1 number (0-9)",
    "độ dài tối thiểu 6 ký tự": "Minimum length 6 characters",
    "ghi nhớ": "Remember Me",
    "quên mật khẩu?": "Forgot Password?",
    "đăng nhập ngay": "Log In Now",
    "đăng nhập bằng thiết bị an toàn": "Log In with Secure Device",
    "quay lại đăng nhập": "Back to Login",
    "khôi phục mật khẩu": "Reset Password",
    "email đăng ký": "Registered Email",
    "nhập email của bạn": "Enter your email",
    "nhập mã otp đã gửi đến email": "Enter the OTP sent to your Email",
    "nhập mã xác thực 2fa từ ứng dụng authenticator": "Enter the 2FA code from Authenticator app",
    "mật khẩu mới": "New Password",
    "xác nhận mật khẩu mới": "Confirm New Password",
    "nhập lại mật khẩu mới": "Confirm your new password",
    "gửi mã otp": "SEND OTP CODE",
    "chào mừng!": "Welcome!",
    "khám phá thế giới tiện lợi tại ck go.": "Discover the convenience at Convenia.",
    "bạn chưa có tài khoản?": "Don't have an account?",
    "đăng ký ngay": "REGISTER NOW",
    "xác thực 2 lớp (2fa)": "Two-Factor Authentication (2FA)",
    "quét mã qr bằng ứng dụng google authenticator để kích hoạt 2fa.": "Scan the QR code with Google Authenticator app to enable 2FA.",
    "hoặc nhập mã tay": "Or enter code manually",
    "nhập mã xác thực 6 chữ số từ ứng dụng trên điện thoại của bạn": "Enter the 6-digit verification code from your mobile app",
    "xác nhận đăng nhập": "Confirm Login",
    "thiết lập lại 2fa (quét mã qr mới)": "Reset 2FA (Scan new QR code)",
    "quản lý kho ck go": "Convenia Inventory Admin",
    "bảng quản trị kho": "Inventory Panel",
    "thống kê kho": "Stock Summary",
    "tổng số sản phẩm": "Total Products",
    "hết hàng / sắp hết": "Out / Low of Stock",
    "lịch sử cập nhật": "Stock Logs",
    "thêm sản phẩm mới": "Add Product",
    "tên sản phẩm": "Product Name",
    "số lượng": "Quantity",
    "đơn vị": "Unit",
    "hành động": "Action",
    "nhập kho": "Restock",
    "xuất kho": "Dispatch",
    "người thực hiện": "Staff",
    "tải ảnh": "Upload Image",
    "lưu sản phẩm": "Save",
    "về trang chủ": "Go to Homepage",
    "hủy": "Cancel",
    "lịch sử nhập xuất": "Inventory Log",
    "thoát": "Exit",
    "quản lý tồn kho - bình thạnh": "Inventory Management - Binh Thanh",
    "xin chào": "Hello",
    "chọn chi nhánh quản lý": "Select Managed Branch",
    "hình ảnh": "Image",
    "loại": "Type",
    "tồn kho": "Stock",
    "giá bán": "Price",
    "mã sản phẩm (tự động)": "Product ID (Auto)",
    "chọn loại sản phẩm": "Select Product Type",
    "giá bán (vnđ)": "Price (VND)",
    "số lượng tồn": "Stock Quantity",
    "số lượng hiện có": "Available Quantity",
    "hình ảnh sản phẩm (từ máy)": "Product Image (From Device)",
    "lưu vào kho": "SAVE TO INVENTORY",
    "quay lại web": "Back to Website",
    "lịch sử nhập/xuất kho realtime": "Realtime Inventory Logs",
    "dữ liệu được cập nhật tự động khi có biến động kho": "Data is automatically updated when inventory changes",
    "đang quét sản phẩm tại chi nhánh...": "Scanning products at branch...",
    "chi nhánh này hiện chưa có sản phẩm thuộc mục này.": "No products available in this category at this branch.",
    "lỗi tải dữ liệu. vui lòng kiểm tra kết nối với máy chủ api.": "Error loading data. Please check your connection to the API server.",
    "bạn ơi, bạn cần đăng nhập để mua hàng nhé!": "Please log in to make purchases!",
    "không tìm thấy sản phẩm nào khớp với": "No products found matching",
    "quản lý tài khoản": "Manage Profile",
    "cập nhật hồ sơ cá nhân và quản lý bảo mật nâng cao": "Update personal profile and manage advanced security settings",
    "chức vụ": "Role",
    "cập nhật thông tin tài khoản thành công!": "Account profile updated successfully!",
    "lỗi cập nhật!": "Update failed!",
    "thiết bị hoặc trình duyệt này không hỗ trợ fido2/webauthn bảo mật!": "This device or browser does not support secure FIDO2/WebAuthn!",
    "nhập mật khẩu hiện tại của bạn để liên kết thiết bị bảo mật này:": "Enter your current password to link this secure device:",
    "liên kết thất bại: bạn chưa xác nhận mật khẩu.": "Linking failed: You have not confirmed the password.",
    "xác nhận mật khẩu thất bại! vui lòng điền đúng mật khẩu tài khoản.": "Password verification failed! Please enter the correct password.",
    "đã liên kết thiết bị bảo mật vân tay/gương mặt fido2 thành công!": "Successfully linked FIDO2 fingerprint/face security device!",
    "đăng ký fido2 không thành công trên server!": "FIDO2 registration failed on the server!",
    "thao tác bị hủy hoặc trình duyệt không được cấp quyền sinh trắc học.": "Operation cancelled or browser biometric permissions not granted.",
    "lỗi kết nối fido2!": "FIDO2 connection error!",
    "đã tắt xác thực 2 lớp totp!": "Disabled TOTP two-factor authentication!",
    "vui lòng nhập đủ 6 chữ số totp!": "Please enter all 6 digits of the TOTP code!",
    "đã bật thành công bảo mật 2 lớp totp!": "TOTP two-factor authentication enabled successfully!",
    "mã 2fa không chính xác!": "Incorrect 2FA code!",
    "đang quét vị trí của bạn...": "Scanning your location...",
    "đã tìm thấy cửa hàng gần nhất": "Found the nearest store",
    "không thể lấy vị trí. vui lòng bật quyền định vị!": "Unable to get location. Please enable location services!",
    "không thể định vị gps!": "GPS location failed!",
    "trình duyệt không hỗ trợ geolocation!": "Your browser does not support Geolocation!",
    "bảo mật nâng cao": "Advanced Security",
    "khóa fido2 / webauthn": "FIDO2 / WebAuthn Key",
    "đã bật": "ENABLED",
    "tắt": "DISABLED",
    "đăng nhập nhanh bằng cảm biến vân tay hoặc nhận diện khuôn mặt mà không cần nhập mật khẩu.": "Quickly log in using fingerprint sensor or facial recognition without entering password.",
    "liên kết khóa bảo mật": "Link Security Key",
    "xác thực 2 lớp (totp)": "Two-Factor Authentication (TOTP)",
    "bảo vệ tài khoản bằng mã bảo mật 6 số từ google authenticator / microsoft authenticator.": "Protect your account with a 6-digit security code from Google / Microsoft Authenticator.",
    "tắt 2fa": "Disable 2FA",
    "thiết lập 2fa": "Set Up 2FA",
    "mã khóa (secret key)": "Secret Key",
    "đã copy mã 2fa secret!": "2FA secret copied!",
    "nhập mã 6 số từ ứng dụng:": "Enter 6-digit code from app:",
    "xác nhận kích hoạt 2fa": "Confirm Enable 2FA",
    "hủy bỏ": "Cancel",
    "hồ sơ cá nhân": "Personal Profile",
    "email (không đổi)": "Email (ReadOnly)",
    "địa chỉ giao hàng": "Delivery Address",
    "cửa hàng gần nhất (giao nhanh)": "Nearest Store (Fast delivery)",
    "vui lòng nhập mã bảo mật 2 lớp (totp) để tiếp tục!": "Please enter the two-factor authentication (TOTP) code to continue!",
    "đăng nhập thành công! đang chuyển hướng...": "Login successful! Redirecting...",
    "đăng ký tài khoản thành công! hãy đăng nhập ngay.": "Account registered successfully! Please log in now.",
    "có lỗi xảy ra!": "An error occurred!",
    "mã otp 2fa phải gồm đúng 6 chữ số!": "2FA OTP code must be exactly 6 digits!",
    "mã bảo mật 2fa không chính xác!": "Incorrect 2FA security code!",
    "lỗi xác thực: ": "Authentication error: ",
    "trình duyệt hoặc thiết bị của bạn không hỗ trợ fido2/webauthn!": "Your browser or device does not support FIDO2/WebAuthn!",
    "thiết bị bảo mật chưa được đăng ký hoặc không khớp!": "Security device not registered or does not match!",
    "xác thực vân tay/fido2 thành công! đang vào hệ thống...": "Fingerprint/FIDO2 authentication successful! Entering system...",
    "đã hủy thao tác vân tay sinh trắc học.": "Biometric fingerprint operation cancelled.",
    "lỗi xác thực thiết bị fido2!": "FIDO2 device authentication error!",
    "xác thực hai lớp": "Two-Factor Authentication",
    "chào mừng trở lại": "Welcome Back",
    "đăng ký thành viên": "Register Member",
    "nhập mã otp 6 số từ google authenticator trên thiết bị của bạn": "Enter the 6-digit OTP code from Google Authenticator on your device",
    "đăng nhập để nhận ngập tràn ưu đãi tại convenia": "Log in to receive full offers at Convenia",
    "gia nhập convenia premium chỉ trong vài giây": "Join Convenia Premium in just a few seconds",
    "mã bảo mật otp (2fa)": "OTP Security Code (2FA)",
    "xác nhận & đăng nhập": "Confirm & Log In",
    "địa chỉ email": "Email Address",
    "tạo tài khoản": "Create Account",
    "hoặc đăng nhập nhanh": "Or sign in quickly",
    "đăng nhập với vân tay / fido2": "Log in with Fingerprint / FIDO2",
    "chưa có tài khoản? đăng ký ngay": "Don't have an account? Sign up now",
    "đã có tài khoản? đăng nhập ngay": "Already have an account? Log in now",
    "lịch sử mua hàng": "Purchase History",
    "danh sách các đơn hàng đã đặt thành công tại hệ thống convenia": "List of orders successfully placed at Convenia",
    "chưa có đơn hàng nào!": "No orders yet!",
    "hãy đặt món đồ đầu tiên để bắt đầu lưu lịch sử.": "Please place your first order to start saving history.",
    "mua sắm ngay": "Shop Now",
    "tổng thanh toán": "Grand Total",
    "danh sách món ăn": "Item List",
    "số lượng: ": "Quantity: ",
    "còn hàng": "In Stock",
    "trang quản trị hệ thống": "System Administration",
    "cấu hình sản phẩm, kiểm soát số lượng kho hàng tiện lợi": "Configure products and manage inventory conveniently",
    "quản lý sản phẩm": "Product Management",
    "nhật ký kho hàng": "Inventory Logs",
    "cửa hàng:": "Store:",
    "ảnh": "Photo",
    "mã pid": "PID Code",
    "danh mục": "Category",
    "đơn giá": "Price",
    "flash sale": "Flash Sale",
    "đồ ăn": "Food",
    "nước uống": "Drinks",
    "sửa": "Edit",
    "xóa": "Delete",
    "phân loại": "Type",
    "cập nhật sản phẩm": "Update Product",
    "số lượng kho": "Stock Quantity",
    "đơn vị tính": "Unit",
    "chi nhánh cửa hàng": "Store Branch",
    "đường dẫn ảnh": "Image Path",
    "đang tải...": "Uploading...",
    "tải lên": "Upload",
    "sản phẩm tham gia flash sale": "Flash Sale Product",
    "giảm %": "Discount %",
    "cập nhật": "Update",
    "thêm mới": "Add New",
    "tải hình ảnh lên thành công!": "Image uploaded successfully!",
    "lỗi upload file!": "File upload error!",
    "đã chỉnh sửa sản phẩm!": "Product updated!",
    "đã thêm sản phẩm thành công!": "Product added successfully!",
    "thao tác sản phẩm thất bại!": "Product operation failed!",
    "bạn có chắc chắn muốn xóa sản phẩm ": "Are you sure you want to delete product ",
    " không?": "?",
    "đã xóa sản phẩm khỏi hệ thống!": "Product removed from system!",
    "không thể xóa sản phẩm!": "Cannot delete product!",
    "đổi giao diện": "Toggle Theme",
    "sáng": "Light",
    "tối": "Dark",
    "thay đổi ngôn ngữ": "Change Language",
    "giao diện & ngôn ngữ": "Theme & Language",
    "quản trị": "Admin",
    "trang cá nhân": "My Profile",
    "bảng quản trị admin": "Admin Dashboard",
    "trang chủ": "Home",
    "thực đơn": "Menu",
    "tìm kiếm": "Search",
    "chỉ còn": "Only",
    "sản phẩm trong kho!": "items left in stock!"
  },
  ko: {
    "hệ thống ck go": "Convenia 매장 안내",
    "thức ăn & thức uống": "음식 & 음료",
    "thức ăn": "음식",
    "thức uống": "음료",
    "tất cả menu": "전체 메뉴",
    "đăng nhập": "로그인",
    "đăng xuất": "로그아웃",
    "thông tin cá nhân": "내 프로필",
    "quản lý kho": "재고 관리",
    "cửa hàng": "매장",
    "đang xác định...": "위치 확인 중...",
    "giỏ hàng": "장바구니",
    "tìm sản phẩm...": "상품 검색...",
    "tài khoản": "계정",
    "dịch vụ tiện ích": "편의 서비스",
    "ck go tự hào cung cấp các dịch vụ tiện ích đa dạng và chất lượng nhất": "Convenia는 우수한 편의 서비스를 제공하기 위해 최선을 다하고 있습니다",
    "sản phẩm nổi bật": "추천 상품",
    "đăng ký nhận tin khuyến mãi": "뉴스레터 구독",
    "nhập email của bạn...": "이메일을 입력하세요...",
    "đăng ký": "구독하기",
    "phòng chăm sóc khách hàng": "고객지원팀",
    "địa chỉ": "주소",
    "ngày cấp": "등록일",
    "nơi cấp": "등록기관",
    "ưu đãi đặc biệt": "스페셜 혜택",
    "flash sale chớp nhoáng": "번개 플래시 세일",
    "kết thúc trong": "남은 시간",
    "đang tải sản phẩm khuyến mãi từ hệ thống...": "프로모션 상품을 불러오는 중...",
    "gửi": "전송",
    "hệ thống cửa hàng": "매장 찾기",
    "sản phẩm & dịch vụ": "상품 및 서비스",
    "giới thiệu": "회사 소개",
    "cơ hội nghề nghiệp": "채용 정보",
    "tin tức & sự kiện": "뉴스 및 이벤트",
    "liên hệ": "문의하기",
    "điều khoản sử dụng": "이용 약관",
    "chính sách": "개인정보 처리방침",
    "hóa đơn đỏ": "전자 세금계산서",
    "ck convenience store vietnam - chuỗi cửa hàng tiện lợi - mở cửa 24/7": "CK 베트남 편의점 - 24/7 영업 편의점 체인",
    "công ty tnhh bán lẻ ck việt nam - giấy cnđkdn: 0306182043": "CK 베트남 소매 유한회사 - 사업자 등록 번호: 0306182043",
    "ngày cấp: 10/11/2008. nơi cấp: sở kế hoạch - đầu tư tp. hồ chí minh": "발급일: 2008년 11월 10일. 발급기관: 호치민 기획투자국",
    "địa chỉ: 160 bùi thị xuân, phường bến thành, quận 1, thành phố hồ chí minh, việt nam.": "주소: 베트남 호치민시 1군 벤탄동 부이티쑤언 160",
    "phòng chăm sóc khách hàng: 1900.3110": "고객 센터: 1900.3110",
    "email: info@ckstores.com.vn": "이메일: info@ckstores.com.vn",
    "bộ lọc sản phẩm": "상품 필터",
    "chọn chi nhánh": "지점 선택",
    "tất cả chi nhánh": "전체 지점",
    "chi nhánh": "지점",
    "mức giá": "가격 범위",
    "tất cả mức giá": "전체 가격",
    "dưới 15.000đ": "15,000 VND 이하",
    "15.000đ - 30.000đ": "15,000 - 30,000 VND",
    "trên 30.000đ": "30,000 VND 이상",
    "sắp xếp": "정렬 기준",
    "mặc định": "기본",
    "giá tăng dần": "가격 낮은 순",
    "giá giảm dần": "가격 높은 순",
    "còn lại": "재고 수량",
    "phần": "인분",
    "cái": "개",
    "lon": "캔",
    "chai": "병",
    "ly": "컵",
    "mua ngay": "바로 구매",
    "hết hàng": "품절",
    "thêm vào giỏ hàng": "장바구니 담기",
    "giỏ hàng của bạn": "내 장바구니",
    "tổng tiền": "결제 금액",
    "tiến hành thanh toán": "결제하기",
    "thông tin giao hàng": "배송 정보",
    "họ và tên": "성함",
    "số điện thoại": "연락처",
    "địa chỉ nhận hàng": "배송 주소",
    "chọn phương thức thanh toán": "결제수단 선택",
    "thanh toán khi nhận hàng (cod)": "만나서 결제 (COD)",
    "chuyển khoản ngân hàng qua vietqr": "VietQR 계좌 이체",
    "hoàn tất thanh toán": "주문 완료하기",
    "giỏ hàng trống": "장바구니가 비어 있습니다",
    "quay lại mua sắm": "쇼핑 계속하기",
    "tiếp tục mua hàng": "쇼핑 계속하기",
    "đang tải giỏ hàng...": "장바구니를 불러오는 중...",
    "tóm tắt đơn hàng": "주문 요약",
    "tạm tính": "소계",
    "phí vận chuyển": "배송비",
    "miễn phí": "무료",
    "tổng cộng": "합계",
    "thanh toán với vietqr": "VIETQR로 결제",
    "đang xử lý đơn hàng...": "주문 처리 중...",
    "xác thực thanh toán (email otp)": "결제 인증 (이메일 OTP)",
    "nhập mã otp 6 chữ số đã được gửi đến email của bạn để xác nhận giao dịch": "거래를 승인하기 위해 이메일로 전송된 6자리 OTP를 입력하세요",
    "xác nhận thanh toán": "결제 확인",
    "thanh toán chuyển khoản vietqr": "VietQR 계좌 이체 결제",
    "vui lòng quét mã qr dưới đây bằng app ngân hàng để thanh toán": "은행 앱으로 아래 QR 코드를 스캔하여 결제해 주세요",
    "tìm kiếm cửa hàng": "매장 찾기",
    "nhập tên đường, quận...": "도로명, 지역명 입력...",
    "đóng cửa": "영업 종료",
    "mở cửa 24/7": "24시간 영업",
    "khoảng cách": "거리",
    "đường đi": "길찾기",
    "chọn làm cửa hàng mặc định": "기본 매장으로 설정",
    "cửa hàng mặc định": "기본 매장",
    "tính khoảng cách từ vị trí của tôi": "내 위치에서 거리 계산",
    "chỉ đường đi": "길찾기",
    "quản lý thông tin tài khoản": "회원 정보 관리",
    "email đăng nhập": "이메일 계정",
    "ngày sinh": "생년월일",
    "cửa hàng gần nhất": "가장 가까운 매장",
    "lịch sử đơn hàng": "주문 내역",
    "xác thực hai yếu tố (2fa)": "2단계 인증 (2FA)",
    "thiết lập fido2 / passkey": "FIDO2 / 패스키 설정",
    "lưu thay đổi": "설정 저장",
    "kích hoạt 2fa": "2FA 활성화",
    "hủy kích hoạt 2fa": "2FA 비활성화",
    "đăng ký passkey mới": "새 패스키 등록",
    "bạn chưa có đơn hàng nào.": "주문 내역이 없습니다.",
    "hồ sơ thành viên ck go": "Convenia 회원 프로필",
    "nhập họ tên": "성함을 입력하세요",
    "nhập số điện thoại": "전화번호를 입력하세요",
    "cửa hàng ck go gần nhất": "가장 가까운 Convenia 매장",
    "nhấn nút để tìm store...": "버튼을 클릭하여 매장을 찾으세요...",
    "-- chọn chi nhánh --": "-- 지점 선택 --",
    "địa chỉ nhận hàng chi tiết": "상세 배송 주소",
    "số nhà, tên đường...": "건물 번호, 도로명...",
    "xác thực sinh trắc học (fido2)": "생체 인증 (FIDO2)",
    "đăng ký thiết bị an toàn (windows hello / touch id) để đăng nhập và thanh toán nhanh không cần mật khẩu.": "비밀번호 없이 로그인 및 빠른 결제를 위해 보안 기기(Windows Hello / Touch ID)를 등록하세요.",
    "đăng ký thiết bị bảo mật": "보안 기기 등록",
    "xem lịch sử mua hàng": "주문 내역 보기",
    "chi tiết đơn hàng": "주문 상세 내역",
    "mã đơn hàng": "주문 번호",
    "trạng thái": "상태",
    "thời gian": "날짜",
    "thành tiền": "결제 금액",
    "tên đăng nhập / email": "사용자 이름 / 이메일",
    "mật khẩu": "비밀번호",
    "ít nhất 6 ký tự (chữ & số)": "최소 6자 (문자 및 숫자)",
    "nhập lại mật khẩu": "비밀번호 확인",
    "mật khẩu không trùng khớp!": "비밀번호가 일치하지 않습니다!",
    "có ít nhất 1 chữ cái (a-z)": "최소 1개 문자 포함 (a-z)",
    "có ít nhất 1 chữ số (0-9)": "최소 1개 숫자 포함 (0-9)",
    "độ dài tối thiểu 6 ký tự": "최소 6자 이상",
    "ghi nhớ": "자동 로그인",
    "quên mật khẩu?": "비밀번호를 잊으셨나요?",
    "đăng nhập ngay": "지금 로그인",
    "đăng nhập bằng thiết bị an toàn": "보안 기기로 로그인",
    "quay lại đăng nhập": "로그인으로 돌아가기",
    "khôi phục mật khẩu": "비밀번호 재설정",
    "email đăng ký": "등록된 이메일",
    "nhập email của bạn": "이메일을 입력하세요",
    "nhập mã otp đã gửi đến email": "이메일로 전송된 OTP를 입력하세요",
    "nhập mã xác thực 2fa từ ứng dụng authenticator": "인증기 앱의 2FA 코드를 입력하세요",
    "mật khẩu mới": "새 비밀번호",
    "xác nhận mật khẩu mới": "새 비밀번호 확인",
    "nhập lại mật khẩu mới": "새 비밀번호를 다시 입력하세요",
    "gửi mã otp": "OTP 코드 전송",
    "chào mừng!": "환영합니다!",
    "khám phá thế giới tiện lợi tại ck go.": "Convenia에서 편리한 세상을 경험해보세요.",
    "bạn chưa có tài khoản?": "계정이 없으신가요?",
    "đăng ký ngay": "지금 가입하기",
    "xác thực 2 lớp (2fa)": "2단계 인증 (2FA)",
    "quét mã qr bằng ứng dụng google authenticator để kích hoạt 2fa.": "2FA를 활성화하려면 Google Authenticator 앱으로 QR 코드를 스캔하세요.",
    "hoặc nhập mã tay": "또는 수동으로 코드 입력",
    "nhập mã xác thực 6 chữ số từ ứng dụng trên điện thoại của bạn": "모바일 앱의 6자리 인증 코드를 입력하세요",
    "xác nhận đăng nhập": "로그인 확인",
    "thiết lập lại 2fa (quét mã qr mới)": "2FA 재설정 (새 QR 코드 스캔)",
    "quản lý kho ck go": "Convenia 재고 관리",
    "bảng quản trị kho": "재고 관리 대시보드",
    "thống kê kho": "재고 현황 요약",
    "tổng số sản phẩm": "총 상품 수",
    "hết hàng / sắp hết": "품절 / 재고 부족",
    "lịch sử cập nhật": "재고 변 động 로그",
    "thêm sản phẩm mới": "새 상품 등록",
    "tên sản phẩm": "商品名",
    "số lượng": "수량",
    "đơn vị": "단위",
    "hành động": "작업",
    "nhập kho": "입고",
    "xuất kho": "출고",
    "người thực hiện": "담당자",
    "tải ảnh": "이미지 업로드",
    "lưu sản phẩm": "저장하기",
    "về trang chủ": "홈페이지로 이동",
    "hủy": "취소",
    "lịch sử nhập xuất": "입출고 내역",
    "thoát": "나가기",
    "quản lý tồn kho - bình thạnh": "재고 관리 - 빈탄점",
    "xin chào": "안녕하세요",
    "chọn chi nhánh quản lý": "관리할 지점 선택",
    "hình ảnh": "이미지",
    "loại": "분류",
    "tồn kho": "재고",
    "giá bán": "판매가",
    "mã sản phẩm (tự động)": "商品 ID (자동)",
    "chọn loại sản phẩm": "상품 분류 선택",
    "giá bán (vnđ)": "판매가 (VND)",
    "số lượng tồn": "재고 수량",
    "số lượng hiện có": "현재 수량",
    "hình ảnh sản phẩm (từ máy)": "상품 이미지 (기기에서 선택)",
    "lưu vào kho": "재고에 저장",
    "quay lại web": "웹사이트로 돌아가기",
    "lịch sử nhập/xuất kho realtime": "실시간 입출고 내역",
    "dữ liệu được cập nhật tự động khi có biến động kho": "재고 변동 시 데이터가 자동으로 업데이트됩니다",
    "đang quét sản phẩm tại chi nhánh...": "지점 상품 검색 중...",
    "chi nhánh này hiện chưa có sản phẩm thuộc mục này.": "이 지점의 해당 분류에 상품이 없습니다.",
    "lỗi tải dữ liệu. vui lòng kiểm tra kết nối với máy chủ api.": "데이터 로드 오류. API 서버와의 연결을 확인하세요.",
    "bạn ơi, bạn cần đăng nhập để mua hàng nhé!": "구매하려면 로그인해 주세요!",
    "không tìm thấy sản phẩm nào khớp với": "일치하는 상품을 찾을 수 없습니다",
    "quản lý tài khoản": "계정 관리",
    "cập nhật hồ sơ cá nhân và quản lý bảo mật nâng cao": "개인 프로필 업데이트 및 고급 보안 설정 관리",
    "chức vụ": "직무",
    "cập nhật thông tin tài khoản thành công!": "계정 정보가 성공적으로 업데이트되었습니다!",
    "lỗi cập nhật!": "업데이트 실패!",
    "thiết bị hoặc trình duyệt này không hỗ trợ fido2/webauthn bảo mật!": "이 기기 또는 브라우저는 안전한 FIDO2/WebAuthn을 지원하지 않습니다!",
    "nhập mật khẩu hiện tại của bạn để liên kết thiết bị bảo mật này:": "이 보안 장치를 연결하려면 현재 비밀번호를 입력하십시오:",
    "liên kết thất bại: bạn chưa xác nhận mật khẩu.": "연결 실패: 비밀번호가 확인되지 않았습니다.",
    "xác nhận mật khẩu thất bại! vui lòng điền đúng mật khẩu tài khoản.": "비밀번호 확인 실패! 올바른 비밀번호를 입력해 주세요.",
    "đã liên kết thiết bị bảo mật vân tay/gương mặt fido2 thành công!": "FIDO2 지문/안면 보안 장치가 성공적으로 연결되었습니다!",
    "đăng ký fido2 không thành công trên server!": "서버에서 FIDO2 등록이 실패했습니다!",
    "thao tác bị hủy hoặc trình duyệt không được cấp quyền sinh trắc học.": "작업이 취소되었거나 브라우저 생체 인식 권한이 부여되지 않았습니다.",
    "lỗi kết nối fido2!": "FIDO2 연결 오류!",
    "đã tắt xác thực 2 lớp totp!": "TOTP 2단계 인증이 비활성화되었습니다!",
    "vui lòng nhập đủ 6 chữ số totp!": "TOTP 코드 6자리를 모두 입력하세요!",
    "đã bật thành công bảo mật 2 lớp totp!": "TOTP 2단계 인증이 성공적으로 활성화되었습니다!",
    "mã 2fa không chính xác!": "잘못된 2FA 코드입니다!",
    "đang quét vị trí của bạn...": "내 위치 스캔 중...",
    "đã tìm thấy cửa hàng gần nhất": "가장 가까운 매장을 찾았습니다",
    "không thể lấy vị trí. vui lòng bật quyền định vị!": "위치를 가져올 수 없습니다. 위치 서비스를 활성화하세요!",
    "không thể định vị gps!": "GPS 위치 확인 실패!",
    "trình duyệt không hỗ trợ geolocation!": "사용하시는 브라우저는 위치 서비스를 지원하지 않습니다!",
    "bảo mật nâng cao": "고급 보안",
    "khóa fido2 / webauthn": "FIDO2 / WebAuthn 키",
    "đã bật": "활성화됨",
    "tắt": "비활성화됨",
    "đăng nhập nhanh bằng cảm biến vân tay hoặc nhận diện khuôn mặt mà không cần nhập mật khẩu.": "비밀번호 입력 없이 지문 인식이나 안면 인식을 사용하여 빠르게 로그인하세요.",
    "liên kết khóa bảo mật": "보안 키 연결",
    "xác thực 2 lớp (totp)": "2단계 인증 (TOTP)",
    "bảo vệ tài khoản bằng mã bảo mật 6 số từ google authenticator / microsoft authenticator.": "Google / Microsoft Authenticator의 6자리 보안 코드로 계정을 보호하세요.",
    "tắt 2fa": "2FA 비활성화",
    "thiết lập 2fa": "2FA 설정",
    "mã khóa (secret key)": "비밀 키 (Secret Key)",
    "đã copy mã 2fa secret!": "2FA 비밀 키가 복사되었습니다!",
    "nhập mã 6 số từ ứng dụng:": "앱에서 6자리 코드를 입력하세요:",
    "xác nhận kích hoạt 2fa": "2FA 활성화 확인",
    "hủy bỏ": "취소",
    "hồ sơ cá nhân": "개인 프로필",
    "email (không đổi)": "이메일 (읽기 전용)",
    "địa chỉ giao hàng": "배송 주소",
    "cửa hàng gần nhất (giao nhanh)": "가장 가까운 매장 (빠른 배송)",
    "vui lòng nhập mã bảo mật 2 lớp (totp) để tiếp tục!": "계속하려면 2단계 인증(TOTP) 코드를 입력하세요!",
    "đăng nhập thành công! đang chuyển hướng...": "로그인 성공! 이동 중...",
    "đăng ký tài khoản thành công! hãy đăng nhập ngay.": "계정이 성공적으로 등록되었습니다! 지금 로그인하세요.",
    "có lỗi xảy ra!": "오류가 발생했습니다!",
    "mã otp 2fa phải gồm đúng 6 chữ số!": "2FA OTP 코드는 정확히 6자리여야 합니다!",
    "mã bảo mật 2fa không chính xác!": "잘못된 2FA 보안 코드입니다!",
    "lỗi xác thực: ": "인증 오류: ",
    "trình duyệt hoặc thiết bị của bạn không hỗ trợ fido2/webauthn!": "귀하의 브라우저 또는 기기는 FIDO2/WebAuthn을 지원하지 않습니다!",
    "thiết bị bảo mật chưa được đăng ký hoặc không khớp!": "보안 장치가 등록되지 않았거나 일치하지 않습니다!",
    "xác thực vân tay/fido2 thành công! đang vào hệ thống...": "지문/FIDO2 인증 성공! 시스템 접속 중...",
    "đã hủy thao tác vân tay sinh trắc học.": "생체 지문 작업이 취소되었습니다.",
    "lỗi xác thực thiết bị fido2!": "FIDO2 장치 인증 오류!",
    "xác thực hai lớp": "2단계 인증",
    "chào mừng trở lại": "다시 오신 것을 환영합니다",
    "đăng ký thành viên": "회원 가입",
    "nhập mã otp 6 số từ google authenticator trên thiết bị của bạn": "기기에서 Google Authenticator의 6자리 OTP 코드를 입력하세요",
    "đăng nhập để nhận ngập tràn ưu đãi tại convenia": "Convenia에서 제공하는 모든 혜택을 누리려면 로그인하세요",
    "gia nhập convenia premium chỉ trong vài giây": "몇 초 만에 Convenia Premium에 가입하세요",
    "mã bảo mật otp (2fa)": "OTP 보안 코드 (2FA)",
    "xác nhận & đăng nhập": "확인 및 로그인",
    "địa chỉ email": "이메일 주소",
    "tạo tài khoản": "계정 생성",
    "hoặc đăng nhập nhanh": "또는 빠른 로그인",
    "đăng nhập với vân tay / fido2": "지문 / FIDO2로 로그인",
    "chưa có tài khoản? đăng ký ngay": "계정이 없으신가요? 지금 가입하세요",
    "đã có tài khoản? đăng nhập ngay": "이미 계정이 있으신가요? 지금 로그인하세요",
    "lịch sử mua hàng": "구매 내역",
    "danh sách các đơn hàng đã đặt thành công tại hệ thống convenia": "Convenia에서 성공적으로 완료된 주문 목록",
    "chưa có đơn hàng nào!": "아직 주문 내역이 없습니다!",
    "hãy đặt món đồ đầu tiên để bắt đầu lưu lịch sử.": "내역을 저장하려면 첫 주문을 해보세요.",
    "mua sắm ngay": "지금 쇼핑하기",
    "tổng thanh toán": "총 결제 금액",
    "danh sách món ăn": "상품 목록",
    "số lượng: ": "수량: ",
    "còn hàng": "재고 있음",
    "trang quản trị hệ thống": "시스템 관리",
    "cấu hình sản phẩm, kiểm soát số lượng kho hàng tiện lợi": "상품 설정 및 재고 관리",
    "quản lý sản phẩm": "상품 관리",
    "nhật ký kho hàng": "재고 이력",
    "cửa hàng:": "매장:",
    "ảnh": "사진",
    "mã pid": "PID 코드",
    "danh mục": "분류",
    "đơn giá": "단가",
    "flash sale": "플래시 세일",
    "đồ ăn": "음식",
    "nước uống": "음료",
    "sửa": "수정",
    "xóa": "삭제",
    "phân loại": "분류",
    "cập nhật sản phẩm": "상품 수정",
    "số lượng kho": "재고 수량",
    "đơn vị tính": "단위",
    "chi nhánh cửa hàng": "매장 지점",
    "đường dẫn ảnh": "이미지 경로",
    "đang tải...": "업로드 중...",
    "tải lên": "업로드",
    "sản phẩm tham gia flash sale": "플래시 세일 상품",
    "giảm %": "할인 %",
    "cập nhật": "수정",
    "thêm mới": "추가",
    "tải hình ảnh lên thành công!": "이미지 업로드 성공!",
    "lỗi upload file!": "파일 업로드 오류!",
    "đã chỉnh sửa sản phẩm!": "상품이 수정되었습니다!",
    "đã thêm sản phẩm thành công!": "상품이 추가되었습니다!",
    "thao tác sản phẩm thất bại!": "상품 작업 실패!",
    "bạn có chắc chắn muốn xóa sản phẩm ": "정말로 상품을 삭제하시겠습니까: ",
    " không?": "?",
    "đã xóa sản phẩm khỏi hệ thống!": "시스템에서 상품이 삭제되었습니다!",
    "không thể xóa sản phẩm!": "상품을 삭제할 수 없습니다!",
    "đổi giao diện": "테마 변경",
    "sáng": "라이트",
    "tối": "다크",
    "thay đổi ngôn ngữ": "언어 변경",
    "giao diện & ngôn ngữ": "테마 & 언어",
    "quản trị": "관리자",
    "trang cá nhân": "내 프로필",
    "bảng quản trị admin": "관리자 대시보드",
    "trang chủ": "홈",
    "thực đơn": "메뉴",
    "tìm kiếm": "검색",
    "chỉ còn": "재고가",
    "sản phẩm trong kho!": "개 남았습니다!"
  }
}

export function ThemeLangProvider({ children }) {
  const { user } = useAuth()
  const [theme, setTheme] = useState('light')
  const [lang, setLang] = useState('vi')

  const getPrefsId = () => {
    if (user && user.uid) return user.uid
    let guestId = localStorage.getItem("guest_id")
    if (!guestId) {
      guestId = "guest_" + Math.random().toString(36).substring(2, 15)
      localStorage.setItem("guest_id", guestId)
    }
    return guestId
  }

  useEffect(() => {
    const loadPrefs = async () => {
      const prefsId = getPrefsId()
      try {
        const themeRes = await fetch(`/api/settings/theme_${prefsId}`)
        if (themeRes.ok) {
          const themeData = await themeRes.json()
          if (themeData.exists && themeData.value) {
            setTheme(JSON.parse(themeData.value))
          }
        }
        const langRes = await fetch(`/api/settings/lang_${prefsId}`)
        if (langRes.ok) {
          const langData = await langRes.json()
          if (langData.exists && langData.value) {
            setLang(JSON.parse(langData.value))
          }
        }
      } catch (err) {
        console.error("Lỗi tải cài đặt từ Database:", err)
      }
    }
    loadPrefs()
  }, [user])

  useEffect(() => {
    const root = document.documentElement
    if (theme === 'dark') {
      root.classList.add('dark', 'dark-theme')
    } else {
      root.classList.remove('dark', 'dark-theme')
    }
  }, [theme])

  const toggleTheme = async () => {
    const nextTheme = theme === 'light' ? 'dark' : 'light'
    setTheme(nextTheme)
    const prefsId = getPrefsId()
    try {
      await fetch(`/api/settings/theme_${prefsId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ value: JSON.stringify(nextTheme) })
      })
    } catch (err) {
      console.error(err)
    }
  }

  const changeLang = async (nextLang) => {
    setLang(nextLang)
    const prefsId = getPrefsId()
    try {
      await fetch(`/api/settings/lang_${prefsId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ value: JSON.stringify(nextLang) })
      })
    } catch (err) {
      console.error(err)
    }
  }

  const t = (key) => {
    if (!key) return ''
    const lookupKey = key.trim().replace(/\s+/g, ' ').toLowerCase()
    
    let isColon = false
    let searchKey = lookupKey
    if (lookupKey.endsWith(':')) {
      searchKey = lookupKey.slice(0, -1).trim()
      isColon = true
    }

    const dict = translations[lang]
    if (dict && dict[searchKey]) {
      return dict[searchKey] + (isColon ? ':' : '')
    }
    return key
  }

  return (
    <ThemeLangContext.Provider value={{ theme, lang, toggleTheme, changeLang, t }}>
      {children}
    </ThemeLangContext.Provider>
  )
}

export function useThemeLang() {
  return useContext(ThemeLangContext)
}
